services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      F2B_DB_PURGE_AGE: 30d
      F2B_LOG_TARGET: /logs/fail2ban/fail2ban.log
    network_mode: host
    volumes:
      - ./config:/data
      - ./../logs/fail2ban:/logs/fail2ban
      - ./../logs:/logs:ro
