services:
  go2rtc-01:
    image: alexxit/go2rtc:latest
    container_name: go2rtc-01
    restart: always
    volumes:
      - ./config:/config
    environment:
      PRINTER_ADDRESS: ${ENV_PRINTER_ADDRESS_01}
      PRINTER_ACCESS_CODE: ${ENV_PRINTER_ACCESS_CODE_01}
    network_mode: container:wireguard-client-01

  go2rtc-02:
    image: alexxit/go2rtc:latest
    container_name: go2rtc-02
    restart: always
    volumes:
      - ./config:/config
    environment:
      PRINTER_ADDRESS: ${ENV_PRINTER_ADDRESS_02}
      PRINTER_ACCESS_CODE: ${ENV_PRINTER_ACCESS_CODE_02}
    network_mode: container:wireguard-client-02
