services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - --entryPoints.HTTP.http.redirections.entryPoint.to=HTTPS
      - --entryPoints.HTTP.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.email=${ENV_ACME_EMAIL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`${ENV_DOMAIN}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=${ENV_ENTRYPOINTS}
      - traefik.http.routers.dashboard.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${ENV_BASIC_AUTH}
      - traefik.http.routers.dashboard.tls=${ENV_TLS}
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
    networks:
      - traefik_lan
    ports:
      - 80:80
      - 443:443
      - 51820:51820/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./config/acme.json:/acme.json
      - ./../logs/traefik:/logs

networks:
  traefik_lan:
    external: true
