[api]
  dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false

  [providers.file]
    directory = "/etc/traefik/dynamic-conf"
    watch = true

[entryPoints]
  [entryPoints.HTTPS]
    address = ":443"

  [entryPoints.HTTP]
    address = ":80"

  [entryPoints.MYSQL]
    address = ":3306"

  [entryPoints.MC]
    address = ":25565"

[certificatesResolvers.letsencrypt.acme]
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[accessLog]
  addInternals = true
  filePath = "/logs/traefik.log"
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.names]
      "ClientUsername" = "drop"