[api]
  dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false

  [providers.file]
    directory = "/etc/traefik/dynamic-conf"
    watch = true

[entryPoints]
  [entryPoints.HTTPS]
    address = ":443"

  [entryPoints.HTTP]
    address = ":80"

  [entryPoints.MYSQL]
    address = ":3306"

[certificatesResolvers.letsencrypt.acme]
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[accessLog]
  addInternals = true
  filePath = "/logs/traefik.log"
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.names]
      "ClientUsername" = "drop"
    [accessLog.fields.headers]
      defaultMode = "keep"
      [accessLog.fields.headers.names]
        "User-Agent" = "keep"
        "Authorization" = "drop"
        "Content-Type" = "keep"
        "OriginStatusLine" = "keep"