[api]
  dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false

  [providers.file]
    directory = "/etc/traefik/dynamic-conf"
    watch = true

[entryPoints]
  [entryPoints.HTTPS]
    address = ":443"

  [entryPoints.HTTP]
    address = ":80"

[certificatesResolvers.letsencrypt.acme]
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[log]
  filePath = "/logs/traefik.log"
  level = "INFO"

[accessLog]
  addInternals = true
  filePath = "/logs/traefik-access.log"