services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    environment:
      DIUN_PROVIDERS_DOCKER: true
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_NOTIF_MAIL_HOST: ${ENV_DIUN_NOTIF_MAIL_HOST}
      DIUN_NOTIF_MAIL_PORT: ${ENV_DIUN_NOTIF_MAIL_PORT}
      DIUN_NOTIF_MAIL_SSL: ${ENV_DIUN_NOTIF_MAIL_SSL}
      DIUN_NOTIF_MAIL_USERNAME: ${ENV_DIUN_NOTIF_MAIL_USERNAME}
      DIUN_NOTIF_MAIL_PASSWORD: ${ENV_DIUN_NOTIF_MAIL_PASSWORD}
      DIUN_NOTIF_MAIL_FROM: ${ENV_DIUN_NOTIF_MAIL_FROM}
      DIUN_NOTIF_MAIL_TO: ${ENV_DIUN_NOTIF_MAIL_TO}
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
