services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v3
    container_name: immich_server
    restart: always
    healthcheck:
      disable: false
    labels:
      - traefik.enable=true
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - traefik.http.routers.immich.rule=Host(`${ENV_DOMAIN}`)
      - traefik.http.routers.immich.entrypoints=${ENV_ENTRYPOINTS}
      - traefik.http.routers.immich.tls=${ENV_TLS}
      - traefik.http.routers.immich.tls.certresolver=letsencrypt
      - traefik.docker.network=traefik_lan
    environment:
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
      DB_DATABASE_NAME: ${ENV_DB_DATABASE_NAME}
      DB_USERNAME: ${ENV_DB_USERNAME}
      DB_PASSWORD: ${ENV_DB_PASSWORD}
    networks:
      - traefik_lan
      - backend
    depends_on:
      - immich-redis
      - immich-database
    volumes:
      - ./data/library:/data
      - /etc/localtime:/etc/localtime:ro

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3
    container_name: immich_machine_learning
    restart: always
    healthcheck:
      disable: false
    environment:
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
      DB_DATABASE_NAME: ${ENV_DB_DATABASE_NAME}
      DB_USERNAME: ${ENV_DB_USERNAME}
      DB_PASSWORD: ${ENV_DB_PASSWORD}
    networks:
      - backend
      - default
    volumes:
      - model-cache:/cache

  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:70739f85ad2ee01a726a965584a0f94895f01b0c60b3cc8b0aeef11eaa6888cf
    container_name: immich_redis
    restart: always
    healthcheck:
      test: redis-cli ping | grep -q PONG || exit 1
    networks:
      - backend

  immich-database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich_postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      disable: false
    environment:
      POSTGRES_DB: ${ENV_DB_DATABASE_NAME}
      POSTGRES_USER: ${ENV_DB_USERNAME}
      POSTGRES_PASSWORD: ${ENV_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - backend
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  model-cache:

networks:
  traefik_lan:
    external: true
  backend:
    internal: true
