services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ENV_MARIADB_ROOT_PASSWORD}
    networks:
      - mysql_lan
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

networks:
  mysql_lan:
    external: true
