services:
  mariadb:
    image: mariadb:13.0
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ENV_MARIADB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1"
    networks:
      - traefik_lan
    ports:
      - 3306:3306/tcp
    volumes:
      - ${APPDATA:-/opt/infra}/mariadb/data:/var/lib/mysql

networks:
  traefik_lan:
    external: true
