services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    labels:
      - traefik.enable=true
      - traefik.tcp.services.mariadb.loadbalancer.server.port=3306
      - traefik.tcp.routers.mariadb.rule=HostSNI(`*`)
      - traefik.tcp.routers.mariadb.entrypoints=MYSQL
    environment:
      MARIADB_ROOT_PASSWORD: ${ENV_MARIADB_ROOT_PASSWORD}
    networks:
      - traefik_lan
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

networks:
  traefik_lan:
    external: true
