services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.rule=Host(`${ENV_DOMAIN}`)
      - traefik.http.routers.portainer.entrypoints=${ENV_ENTRYPOINTS}
      - traefik.http.routers.portainer.tls=${ENV_TLS}
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
    networks:
      - traefik_lan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  traefik_lan:
    external: true
