services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.http.routers.uptime-kuma.rule=Host(`${ENV_DOMAIN}`)
      - traefik.http.routers.uptime-kuma.entrypoints=${ENV_ENTRYPOINTS}
      - traefik.http.routers.uptime-kuma.tls=${ENV_TLS}
      - traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt
    networks:
      - traefik_lan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

networks:
  traefik_lan:
    external: true
