services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: 'minio server /data --console-address ":9001"'
    labels:
      - traefik.enable=true
      - traefik.http.services.minio-api.loadbalancer.server.port=9000
      - traefik.http.routers.minio-api.service=minio-api
      - traefik.http.routers.minio-api.rule=Host(`${ENV_DOMAIN}`)
      - traefik.http.routers.minio-api.entrypoints=${ENV_ENTRYPOINTS}
      - traefik.http.routers.minio-api.tls=${ENV_TLS}
      - traefik.http.routers.minio-api.tls.certresolver=letsencrypt
      - traefik.http.services.minio-ui.loadbalancer.server.port=9001
      - traefik.http.routers.minio-ui.service=minio-ui
      - traefik.http.routers.minio-ui.rule=Host(`ui.${ENV_DOMAIN}`)
      - traefik.http.routers.minio-ui.entrypoints=${ENV_ENTRYPOINTS}
      - traefik.http.routers.minio-ui.tls=${ENV_TLS}
      - traefik.http.routers.minio-ui.tls.certresolver=letsencrypt
    environment:
      MINIO_ROOT_USER: ${ENV_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ENV_MINIO_ROOT_PASSWORD}
    networks:
      - traefik_lan
    volumes:
      - "./data:/data"

networks:
  traefik_lan:
    external: true
