services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: always
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.udp.services.wireguard.loadbalancer.server.port=51820
      - traefik.http.routers.wireguard.rule=Host(`${ENV_DOMAIN}`)
      - traefik.udp.routers.wireguard.entrypoints=VPN
    environment:
      - PUID=1000
      - PGID=1000
      - PEERS=1
      - SERVERURL=${ENV_DOMAIN}
      - SERVERPORT=51820
    networks:
      - traefik_lan
      - mysql_lan
    volumes:
      - ./data:/config

networks:
  traefik_lan:
    external: true
  mysql_lan:
    external: true
